language: node_js
node_js:
  - node

install:
  - npm install

stages:
  - build
  - test

jobs:
  include:
    - stage: build
      name: "Build RingSpinner"
      script: npm run build
    - stage: test
      name: "Test RingSpinner"
      script: npm run test
